### ISSUE TITLE
SendPage not working?  Diagnostic steps?

### ISSUE THREAD

**Issue by ron-watt** [stadler/SendPage#10]
I depend on SendPage in Chrome, but it stopped working.
I'm using Outlook 14.0.7615.5000  - Chrome is current, Version 49.0.2623.87 m (64-bit)

I re-installed the SendPage Extension, and still nothing. 
Where can I find a troubleshooting list?

**Comment by stadler** [comment]
Hi
Thanks for the bug report.
Did you have a look at the Troubleshoot section here: https://github.com/stadler/SendPage

SendPage only works if mailto Links work. For those to work you need to have a program registered as default mail program and therefore responsible for handling mailto links.
An example of such a mailto link would be: [mailto:test@example.com](mailto:test@example.com)

Details how this can be done on windows for Outlook can be found here:
https://community.adxstudio.com/blogs/shan/2012-12-17-win8-tip-setting-outlook-default-mail-client/

Let me know if it still doesn't work, even though mailto links work.

**Comment by ron-watt** [comment]
It does work now. Thanks.
The link below in this email worked, so did pages on our Joomla site… and then I got a response.

It may have been something disabled and fixed in the latest Microsoft Updates.  I had updates pending.
I can’t be certain that SendPage was NOT working before I started updates… or just after I started, and had yet to reboot.

Now I look, it seems the answers were there to be found.
https://chrome.google.com/webstore/detail/send-page/higemadklcnjhjpgcbnnbpgeeippjjcp?utm_source=chrome-app-launcher-info-dialog


________________________________
Ron Watt  | 613.853.7985 |  www.empowered.ca<http://www.empowered.ca/>

**Comment by janetbx** [comment]
Hi!

I am another poster echoing the recent complaint that "Send This Page" stopped working a few days ago.
I was unable to see any information regarding this issue in the link referenced above (https://chrome.google.com/webstore/detail/send-page/higemadklcnjhjpgcbnnbpgeeippjjcp?utm_source=chrome-app-launcher-info-dialog) and I did not find a Troubleshooting section at
https://github.com/stadler/SendPage .

Please note that it was working fine up till now, which means the various things that needed to be done had in fact been done. Is it possible that these things (registration, etc.) got undone on their own??

It would be good if you could post a response in the Tell The Developer "Problem" section at https://chrome.google.com/webstore/detail/send-page/higemadklcnjhjpgcbnnbpgeeippjjcp/support?hl=en which is where people are requesting help with this recent issue. 

Thanks.

**Comment by ron-watt** [comment]
I suspect my issue was due to Windows Updates...  or other bug fixes. Once I was up to date, the issue was gone.

_____________________
Ron Watt  |  613.853.7985  |  empowerednetworks.com
From: janetbx
Sent: Tuesday, March 22, 2016 5:05 AM
To: stadler/SendPage
Reply To: stadler/SendPage
Cc: Ron Watt
Subject: Re: [SendPage] SendPage not working? Diagnostic steps? (#10)



Hi!

I am another poster echoing the recent complaint that "Send This Page" stopped working a few days ago.
I was unable to see any information regarding this issue in the link referenced above (https://chrome.google.com/webstore/detail/send-page/higemadklcnjhjpgcbnnbpgeeippjjcp?utm_source=chrome-app-launcher-info-dialog) and I did not find a Troubleshooting section at
https://github.com/stadler/SendPage .

Please note that it was working fine up till now, which means the various things that needed to be done had in fact been done. Is it possible that these things (registration, etc.) got undone on their own??

It would be good if you could post a response in the Tell The Developer "Problem" section at https://chrome.google.com/webstore/detail/send-page/higemadklcnjhjpgcbnnbpgeeippjjcp/support?hl=en which is where people are requesting help with this recent issue.

Thanks.

-

**Comment by ron-watt** [comment]
One more thing... Once I had solved my issue, the problem I was having and how to fix it was, seemingly, everywhere, at every turn.

_____________________
Ron Watt  |  613.853.7985  |  empowerednetworks.com
From: janetbx
Sent: Tuesday, March 22, 2016 5:05 AM
To: stadler/SendPage
Reply To: stadler/SendPage
Cc: Ron Watt
Subject: Re: [SendPage] SendPage not working? Diagnostic steps? (#10)



Hi!

I am another poster echoing the recent complaint that "Send This Page" stopped working a few days ago.
I was unable to see any information regarding this issue in the link referenced above (https://chrome.google.com/webstore/detail/send-page/higemadklcnjhjpgcbnnbpgeeippjjcp?utm_source=chrome-app-launcher-info-dialog) and I did not find a Troubleshooting section at
https://github.com/stadler/SendPage .

Please note that it was working fine up till now, which means the various things that needed to be done had in fact been done. Is it possible that these things (registration, etc.) got undone on their own??

It would be good if you could post a response in the Tell The Developer "Problem" section at https://chrome.google.com/webstore/detail/send-page/higemadklcnjhjpgcbnnbpgeeippjjcp/support?hl=en which is where people are requesting help with this recent issue.

Thanks.

-

**Comment by stadler** [comment]
I have a feeling that this problem isn't solved after all.
I experience the same problem on a Mac with Apple Mail as default Mail client. 
However depending on the site I want to execute "send page" on it works or it doesn't.
Working:
* https://www.google.ch/

Not working:
* http://www.tagesanzeiger.ch/
* https://www.voxxed.com/

It seems that the chrome.tabs.update mechanism doesn't work reliably anymore for opening mailto links since the last version of chrome (v49.0).
I will probably have to switch to chrome.tabs.create again which will open a new tab which needs to be closed again... Ugly but seems to be the only reliable solution.

I'll keep you posted when it is fixed...

**Comment by ittayd** [comment]
It doesn't work for me as well. mailto links work.

**Comment by stadler** [comment]
Hi
I finally found some time to solve this and it should work again with version 2.0 with was just deployed.
Please let me know if there are still problems.
Closing this issue in the meantime.

**Comment by janetbx** [comment]
Was working fine yesterday. 
Today I did not get the Send This Page option at all.
**UPDATED CHROME.** WORKS FINE!

Please advise anyone still having trouble to **_update and relaunch_**. You are then asked to give renewed permission for new Send Page.

Thanks for your efforts!

Windows 7 Home Premium 64-bit

**Comment by ron-watt** [comment]
Hmmm.  When I reloaded Chrome, I was prompted to configure Send Page... 
with boxes to add the "undefined" intro and close words... 
It seems the first of the "close" words are creeping into the Link... 

![image](https://cloud.githubusercontent.com/assets/14003260/14159952/1b847628-f6a7-11e5-9d8b-fcee50d141cb.png)

And then it seemed to stop working... I'll try again later, after a reboot.

**Comment by ron-watt** [comment]
Some more details... after a reboot.  

I'm showing Send Page 2.1 now. 
![image](https://cloud.githubusercontent.com/assets/14003260/14160667/c7b18f4a-f6ab-11e5-872b-ee3dabbbffcd.png)

Here's the Send Page config Options... 
![image](https://cloud.githubusercontent.com/assets/14003260/14160651/9d56bffe-f6ab-11e5-9b43-4472d7b9cf16.png)

Simple mailto links work... like http://empowerednetworks.com/support 
But Send Page is no longer working... I tried again to remove and reinstall...

**Comment by geetee24** [comment]
Latest Sendpage v2.1 update is tottally broken.  mailto link works - brings up windows 7 Thunderbird yet SendPage does nothing.  Nada. totally broken.,  how can I revert to the old version that worked for years :(

**Comment by janetbx** [comment]
I didn’t ask me to do any configuring—probably because I didn’t have any configuring before....:-).... Didn’t realize you could put in automatic text—thanks!....:-).... By the way, mine is set to Web Mail Client even though I in fact have a local email client. It seems to work fine as is.....
